Executable document project


** Goal
To generate a version of Pastoll et al. 2020 in which code runs to generate the figures.

** Format
Insert code blocks into the R markdown document. Stencila will convert this document back into an eLife formatted article document.

** Notes

*** Inserted URL for the article at https://hub.stenci.la/open/ and then downloaded the R markdown document.

*** Set up a GitHub repository to contain the converted documents as well as project data and functions.

*** To compile or run the Stenicila converted R markdown document a standard setup block needs to be inserted at the top.

** Questions
<2020-06-06 Sat>
- In the document generated by the Stencila converter some of the figures are shown but others are missing. I can manually add them back but I'm not sure how best to do this without breaking the formating or something else downstream when the document converts back to the publication format. Please advise.
- I see that the text for the figure legends is included as a subheading at a level below the section heading. However, this is missing for several of the figures in the converted document. Is there a fix for this that doesn't involve manually replacing it?
- Is there a model for how / where code blocks should be inserted so that they format correctly in the final document?
- Will executable figures replace the original figures or be generated alongside them?
- How should code blocks associate with Figures and Tables? E.g. Should I add links to the main text as in the same as a standard .Rmd document? Or just leave the code blocks as standalone elements?
- Do we want to execute everything? E.g. Numbers given in the manuscript that come from analyses could be linked directly to the data they come from? Happy try this but will add to the time commitment.
- Can I refer to analysis functions outside the R markdown document? Will 'source' work to run a .R file containing these functions? If so, should I source from the setup code block or somewhere else?
- I'm assuming that I should refer to other files using paths relative to the directory containing the .Rmd file. Will this be ok?
- Should I load packages from the setup block or somewhere else? Can I source a separate initialisation script to do this?
- Is there a quick way to convert the document back to the final format so I can check things are ok as I go along?
- Minor. Having the bibliography at the top of the .Rmd document is a bit annoying. Will it break things later if I move it? Can it be loaded from a separate document?
